name: "Test"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5.0.0"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v6.0.0"
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: "Install dependencies"
        run: "npm clean-install"

      - name: "Test"
        run: "node --run test"
